FROM golang:alpine AS Builder

ARG var_version=devel
ENV VERSION=$var_version

RUN mkdir -p /src
RUN apk update && apk add --no-cache gcc musl-dev make

COPY . /src/stamus-ctl
WORKDIR /src/stamus-ctl

RUN CGO_ENABLED=1 make cli

FROM scratch
COPY --from=Builder /src/stamus-ctl/dist /bin/